/**
 * Sync Hermes cron jobs from app manifests or imperative app events.
 *
 * Manifest `cron.jobs[]` is registered at Joshu boot. no-agent scripts are
 * written into ~/.hermes/scripts/ (Hermes cron cwd) so a declared job actually
 * exists — last30days Watching depends on this.
 */

import fs from "node:fs";
import path from "node:path";

import type { JoshuAppManifest } from "@joshu/app-sdk";

import { loadAppManifests } from "./appRegistry.js";
import { callCronBridge, type CronBridgeJobSummary } from "./hermesCronBridge.js";
import { getHermesHomeDir } from "./hermesVoiceRuntime.js";

export type AppCronJobDef = {
  id: string;
  name?: string;
  schedule: string;
  /** noAgent script under ~/.hermes/scripts/ */
  script?: string;
  noAgent?: boolean;
  prompt?: string;
  skills?: string[];
  deliver?: string;
};

export type ManifestCronJob = {
  id?: string;
  name?: string;
  schedule?: string;
  noAgent?: boolean;
  script?: string;
  prompt?: string;
  skills?: string[];
  deliver?: string;
  invoke?: { action?: string; args?: Record<string, unknown> };
};

type ManifestCronBlock = {
  jobs?: ManifestCronJob[];
};

function readString(value: unknown): string {
  return typeof value === "string" ? value.trim() : "";
}

function hermesCronScriptsDir(): string {
  return path.join(getHermesHomeDir(), "scripts");
}

async function listJobs(): Promise<CronBridgeJobSummary[]> {
  const result = await callCronBridge({ action: "list", include_disabled: true });
  if (!result.success) {
    throw new Error(typeof result.error === "string" ? result.error : "cron list failed");
  }
  return Array.isArray(result.jobs) ? result.jobs : [];
}

/** Upsert a Hermes cron job by stable display name. */
export async function registerAppCronJob(job: AppCronJobDef): Promise<"created" | "updated"> {
  const name = readString(job.name) || job.id;
  const existing = (await listJobs()).find((row) => row.name === name);
  const payload: Record<string, unknown> = {
    schedule: job.schedule,
    name,
    deliver: job.deliver ?? "local",
  };
  if (job.noAgent || job.script) {
    payload.no_agent = true;
    if (job.script) payload.script = job.script;
  }
  if (job.prompt) payload.prompt = job.prompt;
  if (job.skills?.length) payload.skills = job.skills;

  if (existing?.job_id) {
    const result = await callCronBridge({ action: "update", job_id: existing.job_id, ...payload });
    if (!result.success) {
      throw new Error(typeof result.error === "string" ? result.error : `cron update failed for ${name}`);
    }
    return "updated";
  }

  const result = await callCronBridge({ action: "create", ...payload });
  if (!result.success) {
    throw new Error(typeof result.error === "string" ? result.error : `cron create failed for ${name}`);
  }
  return "created";
}

/** Shell body for a no-agent Hermes cron that POSTs app invoke. */
export function buildAppInvokeCronScript(opts: {
  appId: string;
  action: string;
  args?: Record<string, unknown>;
  origin?: string;
  publicBasePath?: string;
}): string {
  const origin = (opts.origin || "http://127.0.0.1:8788").replace(/\/+$/, "");
  const prefix = opts.publicBasePath?.trim() || "/joshu";
  const normalizedPrefix = prefix.startsWith("/") ? prefix : `/${prefix}`;
  const payload = JSON.stringify({
    action: opts.action,
    args: opts.args && Object.keys(opts.args).length ? opts.args : {},
  });
  return `#!/usr/bin/env bash
# Generated by Joshu appCronSync — do not edit; rewritten on Joshu boot.
set -euo pipefail
ORIGIN=${JSON.stringify(origin)}
PREFIX=${JSON.stringify(normalizedPrefix)}
curl -fsS -X POST "\${ORIGIN}\${PREFIX}/api/apps/${opts.appId}/invoke" \\
  -H 'Content-Type: application/json' \\
  --data-binary @- <<'JSON'
${payload}
JSON
`;
}

function writeCronScript(filename: string, contents: string): string {
  const destDir = hermesCronScriptsDir();
  fs.mkdirSync(destDir, { recursive: true });
  const dest = path.join(destDir, filename);
  fs.writeFileSync(dest, contents, { encoding: "utf8", mode: 0o755 });
  return dest;
}

function invokeScriptName(appId: string, jobId: string, action: string): string {
  const safeApp = appId.replace(/[^a-zA-Z0-9._-]/g, "_");
  const safeJob = jobId.replace(/[^a-zA-Z0-9._-]/g, "_");
  const safeAction = action.replace(/[^a-zA-Z0-9._-]/g, "_");
  return `${safeApp}-${safeJob}-${safeAction}.sh`;
}

function installManifestCronScript(
  manifest: JoshuAppManifest,
  row: ManifestCronJob,
): string | undefined {
  const action = readString(row.invoke?.action);
  const named = readString(row.script);
  if (!action && !named) return named || undefined;

  if (action) {
    const filename = named || invokeScriptName(manifest.id, readString(row.id) || action, action);
    writeCronScript(
      filename,
      buildAppInvokeCronScript({
        appId: manifest.id,
        action,
        args: row.invoke?.args,
        origin: process.env.JOSHU_BOX_ORIGIN?.trim() || "http://127.0.0.1:8788",
        publicBasePath: process.env.PUBLIC_BASE_PATH?.trim() || "/joshu",
      }),
    );
    return filename;
  }
  return named || undefined;
}

/** Sync static cron.jobs[] from a multimodal manifest (best-effort). */
export async function syncManifestCronJobs(manifest: JoshuAppManifest & { cron?: ManifestCronBlock }): Promise<number> {
  const jobs = manifest.cron?.jobs ?? [];
  let synced = 0;
  for (const row of jobs) {
    const schedule = readString(row.schedule);
    const id = readString(row.id);
    if (!schedule || !id) continue;

    const script = installManifestCronScript(manifest, row);

    await registerAppCronJob({
      id,
      name: readString(row.name) || `${manifest.name}: ${id}`,
      schedule,
      noAgent: row.noAgent ?? Boolean(script),
      script: script || undefined,
      prompt: readString(row.prompt) || undefined,
      skills: row.skills,
      deliver: readString(row.deliver) || "local",
    });
    synced += 1;
  }
  return synced;
}

/** Load every app manifest and upsert declared Hermes cron jobs. */
export async function syncAllAppManifestCronJobs(projectRoot: string): Promise<number> {
  const manifests = await loadAppManifests(projectRoot);
  let synced = 0;
  for (const manifest of manifests.values()) {
    synced += await syncManifestCronJobs(manifest as JoshuAppManifest & { cron?: ManifestCronBlock });
  }
  return synced;
}
